### ISSUE TITLE
Clarification regarding neume.js and timbre.js

### ISSUE THREAD

**Issue by echo66** [mohayonao/neume.js#59]
Greetings!

What are the main novelty in neume.js, if we compare it with timbre.js? Is it "just" because you added workers to the scheduling & transport components?

**Comment by mohayonao** [comment]
timbre.js uses ScriptProcessor, so it has performance problems.
neume.js doesn't use ScriptProcessor, it aims to provide optimized interfaces to Web Audio API.

**Comment by echo66** [comment]
Thanks for the quick response, mohayonao! I recommend that you include that clarification in the README.md.
