### ISSUE TITLE
"Sched" example not working

### ISSUE THREAD

**Issue by echo66** [mohayonao/neume.js#60]
Greetings!

I'm trying to run the following code:

``` javascript
function Foo($, freq, dur) {
  var out;

  out = $("sin", { freq: freq, mul: 0.25 });
  out = $("xline", { dur: dur }, out).on("end", function(e) {
    this.stop(e.playbackTime);
  });

  return out;
}

neu.Sched(function(e) {
  var freq = e.count ? 440 : 880;
  Neume.Synth(Foo, freq, 0.75).start(e.playbackTime);
  return { next: "+" + (e.count + 2) + "n" };
}).start().stop("+10");
```

but, unfortunately, the browser throws the following error: 
  neume.js:1216 Uncaught TypeError: undefined is not a function

**Comment by mohayonao** [comment]
`neu.Sched` receives a function that returns an iterator.

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Iteration_protocols

``` js
neu.Sched(function(e) {
  var freq = e.count ? 440 : 880;
  neu.Synth(Foo, freq, 0.75).start(e.playbackTime);
  return { 
    next: function() {
      return {
        value: "+" + (e.count + 2) + "n",
        done: false
      };
    };
  };
}).start().stop("+10");
```

I'm going to redesign neume.js in the near future.
Maybe, the specification for scheduling will be changed.

**Comment by echo66** [comment]
thanks for the clarification, mohayonao!

**Comment by echo66** [comment]
I just noticed one thing: the function that returns the "next" does not have access to the "e.count".

In sched.js, we have this in line 87:

``` javascript
var result = _this._schedIter.next();
```

There is no object passed as argument to both "next" and "_schedIter".

**Comment by mohayonao** [comment]
`_schedIter.next()` should return an iteration object that contains duration for next schedule.

e.g.

``` js
var result = _this._schedIter.next();

// result
{ value: 0.5, done: false } // run next schedule after 500ms
```

For sure, this specification is awkward to use.
Maybe, I will change this specification.

**Comment by echo66** [comment]
Well, it is awkward. Maybe that is the reason why I got confuse.

Still, thanks for the quick reply! :)
